export const GET_ALL_COURSES = 'GET_ALL_COURSES';
export const GET_USERS = 'GET_USERS';
export const GET_ADMINS = 'GET_ADMINS';
export const SEARCH_BY_NAME = 'SEARCH_BY_NAME';
export const GET_FAVORITE_COURSES = 'GET_FAVORITE_COURSES';
export const GET_COURSE_DETAILS = 'GET_COURSE_DETAILS';
export const FILTER_BY = 'FILTER_BY';
export const ORDER_BY = 'ORDER_BY';
export const GET_GENRES_COURSES = 'GET_GENRES_COURSES'
export const LOGIN = 'LOGIN'
export const LOGEADO = 'LOGEADO'
export const ADD_CART='ADD_CART'
export const REMOVE_CART = 'REMOVE_CART'
export const ADD_DETAILS = 'ADD_DETAILS'
export const SET_COURSE_TOAPROVE = 'SET_COURSE_TOAPROVE'
export const CONFIRM_ORDER = 'CONFIRM_ORDER'
export const PENDING_ORDER = 'PENDING_ORDER'
export const CLEAR_CART = 'CLEAR_CART'
